name: Documentation

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v1
              with:
                  node-version: "14.16.0"

            - name: Install deps
              run: npm install -D

            - name: Build docs
              run: npm run docs:api && npm run docs:build

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.1.0
              with:
                  branch: gh-pages
                  folder: docs/dist
